"""Pinned Lucide subset for the WS-3 UI theming track."""

LUCIDE_STATIC_VERSION = "1.23.0"
LUCIDE_STATIC_BASE_URL = f"https://unpkg.com/lucide-static@{LUCIDE_STATIC_VERSION}"
LUCIDE_REPOSITORY = "https://github.com/lucide-icons/lucide"

# lucide-static@1.23.0 中与 Feather 名单项几何完全相同的新命名别名。
# 这些映射已用固定 npm tarball 的 SVG 几何逐对核验，许可证按 MIT 保守继承。
FEATHER_DERIVED_ALIASES = {
    "circle-minus": "minus-circle",
    "circle-plus": "plus-circle",
    "circle-x": "x-circle",
    "octagon-alert": "alert-octagon",
}

_UI_ICON_BASE = [
    "activity",
    "air-vent",
    "alarm-clock",
    "alert-circle",
    "alert-triangle",
    "archive",
    "arrow-down",
    "arrow-down-circle",
    "arrow-down-left",
    "arrow-down-right",
    "arrow-left",
    "arrow-left-circle",
    "arrow-right",
    "arrow-right-circle",
    "arrow-up",
    "arrow-up-circle",
    "arrow-up-left",
    "arrow-up-right",
    "at-sign",
    "award",
    "badge-check",
    "ban",
    "bar-chart-3",
    "battery",
    "bell",
    "bell-off",
    "bluetooth",
    "book",
    "bookmark",
    "box",
    "briefcase",
    "calendar",
    "camera",
    "cast",
    "check",
    "check-circle",
    "chevron-down",
    "chevron-left",
    "chevron-right",
    "chevron-up",
    "circle",
    "clipboard",
    "clock",
    "cloud",
    "code",
    "cog",
    "command",
    "compass",
    "copy",
    "credit-card",
    "database",
    "download",
    "edit",
    "external-link",
    "eye",
    "eye-off",
    "file",
    "file-check",
    "file-plus",
    "file-text",
    "filter",
    "flag",
    "folder",
    "folder-open",
    "gauge",
    "globe",
    "grid",
    "heart",
    "help-circle",
    "home",
    "image",
    "inbox",
    "info",
    "key",
    "laptop",
    "layout",
    "link",
    "list",
    "loader",
    "lock",
    "log-in",
    "log-out",
    "mail",
    "map",
    "menu",
    "message-circle",
    "mic",
    "minus",
    "monitor",
    "moon",
    "more-horizontal",
    "more-vertical",
    "move",
    "music",
    "navigation",
    "package",
    "pause-circle",
    "pen-tool",
    "percent",
    "phone",
    "play-circle",
    "plug",
    "plus",
    "plus-circle",
    "power",
    "printer",
    "radio",
    "refresh-ccw",
    "refresh-cw",
    "repeat",
    "save",
    "search",
    "send",
    "server",
    "settings",
    "share",
    "shield",
    "shopping-bag",
    "sidebar",
    "smartphone",
    "smile",
    "star",
    "tag",
    "target",
    "terminal",
    "thumbs-up",
    "trash",
    "trash-2",
    "triangle",
    "truck",
    "tv",
    "upload",
    "user",
    "user-check",
    "user-plus",
    "users",
    "video",
    "volume-2",
    "wallet",
    "wifi",
    "wrench",
    "x",
    "x-circle",
    "zap",
    "zoom-in",
    "zoom-out",
]


# P-UI 高频扩容：只收录固定 lucide-static@1.23.0 中已核验存在的 SVG。
# 8 个 param_engine 按需示范 glyph 有意不在此处重复注册。
_UI_ICON_EXPANSION = [
    # 导航与方向
    "arrow-down-to-line",
    "arrow-up-from-line",
    "chevrons-down",
    "chevrons-left",
    "chevrons-right",
    "chevrons-up",
    "corner-down-left",
    "corner-down-right",
    "corner-left-down",
    "corner-left-up",
    "corner-right-down",
    "corner-right-up",
    "corner-up-left",
    "corner-up-right",
    "locate",
    "map-pin",
    "navigation-2",
    "route",
    "signpost",
    "unfold-horizontal",
    # 操作与编辑
    "bold",
    "clipboard-copy",
    "crop",
    "eraser",
    "grab",
    "hash",
    "italic",
    "link-2",
    "paintbrush",
    "paperclip",
    "pencil",
    "redo-2",
    "rotate-ccw",
    "rotate-cw",
    "scissors",
    "strikethrough",
    "type",
    "underline",
    "undo-2",
    "wand-sparkles",
    # 状态与反馈
    "badge-alert",
    "badge-help",
    "badge-info",
    "badge-minus",
    "badge-plus",
    "badge-x",
    "check-check",
    "circle-check",
    "circle-dot",
    "circle-ellipsis",
    "circle-minus",
    "circle-plus",
    "circle-x",
    "loader-circle",
    "octagon-alert",
    "shield-alert",
    "shield-check",
    "shield-x",
    "sparkles",
    "thumbs-down",
    # 通信与媒体
    "audio-lines",
    "circle-play",
    "forward",
    "headphones",
    "message-square",
    "messages-square",
    "mic-off",
    "podcast",
    "reply",
    "rss",
    "skip-back",
    "skip-forward",
    "volume-1",
    "volume-x",
    "webcam",
    # 文件与数据
    "chart-area",
    "chart-bar",
    "chart-line",
    "chart-pie",
    "clipboard-check",
    "file-archive",
    "file-code",
    "file-down",
    "file-image",
    "file-json",
    "file-lock",
    "file-search",
    "file-up",
    "folder-plus",
    "folders",
    "table",
    "table-2",
    # 设备、连接、商业与安全
    "battery-full",
    "battery-low",
    "cloud-download",
    "cloud-upload",
    "ethernet-port",
    "fingerprint",
    "hard-drive",
    "laptop-minimal",
    "lock-keyhole",
    "shield-user",
    "shopping-cart",
    "sun",
]

UI_ICON_SUBSET = sorted([*_UI_ICON_BASE, *_UI_ICON_EXPANSION])
